apiVersion: serving.kserve.io/v1alpha1
kind: InferenceGraph
metadata:
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  name: model-chainer
spec:
  nodes:
    root:
      routerType: Sequence
      steps:
        - serviceUrl: https://sklearn-iris-predictor-ensemble-test.apps.vedant.ll1b.p1.openshiftapps.com/v2/models/sklearn-iris/infer
        - serviceUrl: https://xgboost-iris-predictor-ensemble-test.apps.vedant.ll1b.p1.openshiftapps.com/v2/models/xgboost-iris/infer
          data: $request
